wandb_version: 1

model_name:
  desc: null
  value: D
experiment:
  desc: null
  value: N
subject_id:
  desc: null
  value: S
optimizer:
  desc: null
  value: adam
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value:
  - '.1'
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682646967.104015
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.10
      5: 0.14.2
      8:
      - 1
      - 5
